.github/workflows/dotnet.yml

Hot off the presses, and with a tar API change that we should consume sooner rather than later.

Move to .NET 7 Preview 6

---

System.Containers/Class1.cs
System.Containers/Image.cs
System.Containers/Layer.cs
System.Containers/Registry.cs
Test.System.Containers.Filesystem/DockerRegistryManager.cs
Test.System.Containers.Filesystem/EndToEnd.cs
Test.System.Containers.Filesystem/LayerEndToEnd.cs
Test.System.Containers.Filesystem/RegistryTests.cs

This introduces a new test that does an end-to-end "realistic" scenario:
1. Get packable bits from a .NET project
2. Pull a base image
3. Create a layer from the published output of the project
4. Update the image with that layer + an entrypoint
5. Push that image up to a local registry
6. Pull it back and run it, validating expected output.

Use local registry for an end-to-end test

---

System.Containers/Layer.cs
Test.System.Containers.Filesystem/LayerEndToEnd.cs

Add a way to specify a list of files to put in the layer, which is more in line with how MSBuild's `ITaskItem[]` will work.

Layer.FromFiles

---

Directory.Packages.props
Directory.Solution.targets
System.Containers.sln
System.Containers/Registry.cs
Test.System.Containers.Filesystem/EndToEnd.cs
containerize/Program.cs
containerize/Properties/launchSettings.json

This adds
* 2 targets for starting a local Docker registry and preloading it with the dotnet base images
* unified references to port 5000 over to 5010 to get out of the default port selection for ASP.NET (and others)
* adds some logging while things are happening
* sets some defaults for common image properties so that we have a nicer-looking UI for the base case (demos better)
* preloads the generated image into the local Docker cache for easier running

UX pass on containerize app 

---

System.Containers/Configuration.cs
System.Containers/ContentStore.cs
System.Containers/Image.cs
System.Containers/Layer.cs
System.Containers/LocalDocker.cs
System.Containers/Registry.cs
Test.System.Containers.Filesystem/EndToEnd.cs
Test.System.Containers.Filesystem/LayerEndToEnd.cs
containerize/Program.cs
containerize/Properties/launchSettings.json

Emit a tarball in a format like `docker save` emits, and make it so we can stream that into `docker load` in a subprocess to avoid the "push to a registry then pull from a registry" dance during inner loops.
Closes #19.

Load image into local Docker without registry push/pull

---

System.Containers.Tasks/build/System.Containers.Tasks.targets

Self-contained applications only need the runtime-deps (regardless of aspnet-ed-ness) so we can use that base image as the default. This image has the same tags as the other base images, so it should be a safe change.

Use dotnet/runtime-deps as the base image for SelfContained scenarios

---

.github/workflows/dotnet.yml
Directory.Build.props
Directory.Packages.props
azure-pipelines.yml
global.json

- Set up signed build with Azure Pipelines
- Update azure-pipelines.yml for Azure Pipelines
- Adopt MicroBuild.Core
- global.json with prerelease
- Always upload logs/bin
- Restore
- Minimal official build console output (binlog ftw)
- Save binlog to staging directory for upload
- Remove Pack target (we pack on build anyway)

Signed official build in internal Azure DevOps

---

.github/workflows/publish-package.yml

We need to actually clone the push target's history so that nerdbank works.

fix ref for main on pushes

---

Microsoft.NET.Build.Containers/build/Microsoft.NET.Build.Containers.props
docs/INTEGRATED-DEMO.md

After the namespace simplification, the UsingTask paths for the two tasks was incorrect.
I'm unsure why the tests I wrote didn't just blow up as a result of this, though.

fix UsingTask declarations so that tasks can be consumed

---

Directory.Build.props
Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Microsoft.NET.Build.Containers/README.md
docs/ContainerCustomization.md
docs/GettingStarted.md

This adds a getting started and configuration set of documentation, as well as a README for the package. The package README is a slight repackaging of the docs\ content that links to it here as the authoritative source.
I also removed the repo-global packagerefs from the publicly-visible package dependencies.
Closes #78

Add help documentation to repo

---

Microsoft.NET.Build.Containers/README.md
docs/GettingStarted.md

We also only support WebSDK projects currently, so we should declare that up-front.

add note about WebSDK support

---

Microsoft.NET.Build.Containers/ContainerHelpers.cs
Microsoft.NET.Build.Containers/ParseContainerProperties.cs
Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs

Closes #106
Instead of just telling the user about the error, we check the shape of the input and
* lower the first character if it's alphanumeric and uppercase
* replace any non-alpha, non-number, non-dash/dot/underscore character with a dash
* error if the first character is anything non-viable
If we had to normalize at all, we log a message so the user can potentially do something about it.

Autocorrect image names if they are correctable

---

Microsoft.NET.Build.Containers/Layer.cs

Closes #109 
DirectoryInfo has a handy method to walk the entire tree from a starting directory, so we use that so that we don't miss anything.
Note that this isn't enough to make an `mvc` template app Just Work out of the box. I can exec onto the container and verify that the `wwwroot` folder exists, and that the contents of that folder match the publish outputs from a local build.
Unsure how to get the Static Files handler to log high enough to verify if this is our problem or something else.
Other things I noticed - even if the internal port on the container is 80, and ASPNETCORE_URLS is set to *:80, I _think_ the external port mapping of (for example) localhost:5010 results in routing mismatches, because the app is bound to :80, so it doesn't recognize the route.

Recursively walk input files to include in the container

---

Microsoft.NET.Build.Containers/CreateNewImage.cs

Many runtime properties are set off of the working directory of the process, including webapp content roots.

Set image working directory

---

Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/Image.cs
Microsoft.NET.Build.Containers/build/Microsoft.NET.Build.Containers.targets

Adds support for `ContainerLabel` item group properties.
```
<ItemGroup>
<ContainerLabel Include="com.microsoft.created-by" Value="dotnet-sdk" />
<ContainerLabel Include="com.microsoft.project-name" Value="$(MSBuildProjectName)" />
</ItemGroup>
```

Add support for Labels to the Image config

---

Microsoft.NET.Build.Containers/ContainerHelpers.cs
Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs

Fixes #116 
It turns out that image names must be lower cased. In addition, we weren't handling `/`-delimited image names (like `dotnet/runtime`).

More correct image name normalization

---

Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj

The 0.1.6 package couldn't be pushed to NuGet due to invalid MS metadata. I consulted the docs and updated the values to the correct ones.  Once this is merged I'll sync to the internal repo and trigger another signed build.

Correct package metadata to enable publishing

---

Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
azure-pipelines.yml

- Cherry pick to v0.1 - More correct image name normalization (#119) (#129)
- Fix v0.1 repo url (#134)
- Correct package metadata to enable publishing (#136)
- Plumb signing parameter down to actual build

Merge final 0.1.8 commit to main

---

Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj

This isn't generally appropriate for production software, but
since we're in an early preview I think we'll get the best bug
reports if .NET can get every bit of information that it can.

Embed debug symbols always

---

Microsoft.NET.Build.Containers/build/Microsoft.NET.Build.Containers.targets

If a user explicitly asks for containerization we should be able to tell them if it's not supported.
Strictly speaking this means that they need to be on 7.0.100-preview.7 or higher.
If they are using a custom publish profile, they will have set the WebPublishMethod explicitly, so we can check that to cover that case. If they are using the default publish profile, they will never actually load the nonexistent profile on unsupported SDK versions, so we should check for the explicit use of the default profile.

Add a build error if building on an unsupported SDK

---

Microsoft.NET.Build.Containers/Image.cs

The cast to JsonValue could conceivably fail, but JsonValue.Create is well annotated.

Fix a CS8600

---

CONTRIBUTING.md

The dotnet/coreclr repo is no longer active. Change the link to point to dotnet/runtime.
See also https://github.com/dotnet/new-repo/pull/12.

Update Contributing link

---

Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/ParseContainerProperties.cs
Microsoft.NET.Build.Containers/build/Microsoft.NET.Build.Containers.targets
Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs
Test.Microsoft.NET.Build.Containers.Filesystem/ParseContainerPropertiesTests.cs
docs/ContainerCustomization.md

Closes #137 
This parses the user's input tags as a semicolon-delimited list, and then iterates through that list during image Push - which should be slow for the first tag and much faster for subsequent tags.  Each tag is validated individually and errors are reported for the incorrect ones only.

Support building multiple tags at once

---

Microsoft.NET.Build.Containers/Image.cs
Microsoft.NET.Build.Containers/Layer.cs
Test.Microsoft.NET.Build.Containers.Filesystem/LayerEndToEnd.cs

Instead of creating and disposing an intermediate SHA256 object, use the static APIs directly. Also avoid allocating a temporary byte[] on the heap, and instead just stackalloc the hash bytes.

Use SHA256 OneShot APIs

---

Microsoft.NET.Build.Containers/Descriptor.cs
Microsoft.NET.Build.Containers/Image.cs
Microsoft.NET.Build.Containers/Layer.cs
Test.Microsoft.NET.Build.Containers.Filesystem/LayerEndToEnd.cs

Compressing the `.tar` files to make the layer files smaller.
Fix #29
cc @rainersigwald 
Are there other tests I should be adding / modifying?

Implement gz compression

---

Microsoft.NET.Build.Containers/ContainerHelpers.cs
Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/Image.cs
Test.Microsoft.NET.Build.Containers/ContainerHelpersTests.cs
containerize/Program.cs
containerize/containerize.csproj
packaging/build/Microsoft.NET.Build.Containers.targets

This is a fairly mechanical transformation.  Things remaining to do:
* tests to verify the addition of the default aspnetcore port declarations (or not, as appropriate)
* tests to verify deduping
* add warnings for malformed ContainerPort Items

Add support for ExposedPorts to the Image config

---

nuget.config

This is required for internal Microsoft compliance reasons.

Switch to the dotnet-public NuGet feed

---

.github/workflows/dotnet.yml
containerize/Program.cs

For example, see https://github.com/dotnet/sdk-container-builds/pull/161/files#diff-591e9731d0a9220c8d3fda878a4680c7fc58191d16d717e16a74b01b23680cfeR22
Compare to the errors from this build:

Avoid doubled error reports in GitHub Actions

---

packaging/build/Microsoft.NET.Build.Containers.targets

VS has a scenario where `PublishImageTag` is a relevant property and should override our default tag property.
Closes #177

Check for PublishImageTag in VS land

---

packaging/build/Microsoft.NET.Build.Containers.targets

VS scenario compat for auto generating timestamped tags when requested.
When:
- `AutoGenerateImageTag` is `true`
- `PublishImageTag` is empty 
- ~and `RunningInVisualStudio` is `true`~ removed after consulting with @vijayrkn 
Set `ContainerImageTag` to a UTC timestamp of the current time, in the format of: `yyyyMMddhhmmss`

AutoGenerateImageTag sets ContainerImageTag to UTCNow

---

Microsoft.NET.Build.Containers/Registry.cs

Tell GetAsync to return as soon as headers are read, before content is available,
so the full blob content doesn't have to be in memory and can be streamed to
its destination as it downloads.

Don't download entire blob before moving on

---

Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs

Prior to this, some tests were passing by coincidence and order dependence:
`EndToEnd_NoAPI` pushed a container labeled `1.0`, but pulled one labeled `latest`.
That worked because another test pushed `dotnetcontainers/testimage:latest`.

Give each EndToEnd test a unique container name

---

packaging/build/Microsoft.NET.Build.Containers.targets

Fill in target image name as given by @vijayrkn, and centralize all the VS-specific defaults in one location for easier review.

centralize VS properties for target image name and tag

---

Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/ContainerHelpers.cs
Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
Microsoft.NET.Build.Containers/Image.cs
Microsoft.NET.Build.Containers/ParseContainerProperties.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs
Test.Microsoft.NET.Build.Containers.Filesystem/DockerRegistryManager.cs
Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs
containerize/Program.cs
packaging/build/Microsoft.NET.Build.Containers.targets

Fixes https://github.com/dotnet/sdk-container-builds/issues/179
Containerize, CreateNewImage, CreateNewImage (the tool task), and the targets have been modified to flow Environment Variables.
Also added a unit test that verifies it works by Console.Writing the value of the environment variable manually passed into the ParseContainerProeprties task.
Recommend a commit-by-commit review

Support ContainerEnvironmentVariables

---

Microsoft.NET.Build.Containers/CreateNewImage.cs
packaging/build/Microsoft.NET.Build.Containers.targets

In https://github.com/dotnet/sdk-container-builds/pull/196 we started using a null value of OutputRegistry to signal that the push was to a local docker daemon. As a result, we need the OutputRegistry property to no longer be Required.

Allow OutputRegistry to be set to null

---

Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
packaging/build/Microsoft.NET.Build.Containers.targets

This should let us post-hoc investigate the manifests and configurations generated for the image.
I have no idea how to do similar for the tooltask, though - I guess we'd need to shim the `Execute()` member and look for special kinds of output from the executable?

Emit container manifest and config as msbuild items where possible

---

Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/ParseContainerProperties.cs
Microsoft.NET.Build.Containers/Registry.cs
Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs

This logs a bit more during the build, especially around pushing layer and metadata blobs to the registry.
I mostly did this to help with debugging with @vijayrkn, so the levels will need to be tweaked as well.

Add more verbose logging during the build

---

Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
Microsoft.NET.Build.Containers/Credentials/CredentialRetrievalException.cs
containerize/Properties/launchSettings.json

Example new `containerize` output is still not pretty but has more info!
```
Containerize: Uploading layer sha256:bd159e379b3b1bc0134341e4ffdeab5f966ec422ae04818bb69ecef08a823b05 to registry
Containerize: error CONTAINER001: Failed to push to output registry: System.AggregateException: One or more errors occurred. (Failed retrieving credentials for "rainercontainer.azurecr.io": Failed to execute 'docker-credential-desktop get':
credentials not found in native keychain
)
---> Microsoft.NET.Build.Containers.Credentials.CredentialRetrievalException: Failed retrieving credentials for "rainercontainer.azurecr.io": Failed to execute 'docker-credential-desktop get':
credentials not found in native keychain
---> Valleysoft.DockerCredsProvider.CredsNotFoundException: Failed to execute …
```

Cred retrieval failure info++

---

Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs
packaging/build/Microsoft.NET.Build.Containers.targets

Two primary goals here:
* Update the language in the existing version-check message to refer to 7.0.100 stable, since we are very close to GA.
* Expand the version checks to allow building on .NET 8 SDKs.

More exhaustive future-facing checks for supported SDK versions

---

Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs

AWS requests the use of the `Basic` scheme for their auth call-and-responses, so we need to be able to handle that. It's quite easy - if any registry requests basic auth, then we should do an HTTP basic auth with the discovered username and password.

Handle registry authentication requests that use the Basic scheme

---

Microsoft.NET.Build.Containers/Registry.cs

This happens at least sometimes on ACR push.

Allow response location to be null

---

packaging/build/Microsoft.NET.Build.Containers.targets

We currently support only Linux base images, so add an explicit error
in other cases.

Explicit error on non-Linux

---

Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs

Various lists of parameters weren't being aggregated correctly on the `containerize` tool call, which led to failures during publishing.  Instead of rolling our own Aggregate, I used String.Join to handle the logic and the commandlines were corrected, and publishes resumed working.
I found this while adding additional Labels to a publish, but verified the problem with tags as well.

Fix aggregation of lists of parameters to the tool task

---

Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
Microsoft.NET.Build.Containers/AuthHeaderCache.cs

The last attempt at caching was too general and got backed out in #223. What we really want is by "scope" but we don't have a great way to predict a scope in advance, they're generally given back by the server.
This time, I'm trying to cache by URL (excluding query string), which will be very helpful when hitting chunked upload URLs over and over.
See details in the second commit message especially.
- Enable auth caching by URL
- Quirk for ACR 401 on ".../blobs/uploads/"

Auth caching, attempt 2

---

Microsoft.NET.Build.Containers/Registry.cs

Trying to follow modern best practices around HttpClient as I understand them:
- Use a single HttpClient to optimize connections
- Use SocketsHttpHandler

Long-lived HttpClient

---

Microsoft.NET.Build.Containers/ParseContainerProperties.cs
Test.Microsoft.NET.Build.Containers.Filesystem/ParseContainerPropertiesTests.cs

A logic error caused ParseContainerProperties to fail if multi-valued
tags were passed into ContainerImageTags. A test error made that non-
obvious.
Fix the tests to use CollectionAssert methods, and invert the check
on TryValidateTags so that when the tags are valid we respect them.
Fixes #236.

Support tags passed into ParseContainerProperties

---

Microsoft.NET.Build.Containers/CreateNewImage.Interface.cs
Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj

Define the inputs and outputs of the two task implementations in a single
file, pulled into both classes.
Fixes #171.

Single definition for task inputs/outputs

---

Microsoft.NET.Build.Containers/CreateNewImage.Interface.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs

If something caused ImageTags to be empty, the foreach-tag-push loop
would silently do nothing, which is a confusing user experience.
Instead, emit an error and fail. Fixes #240.

Error when no tags are given to CreateNewImage

---

Microsoft.NET.Build.Containers/Layer.cs

Fix #246
___________
I'm not sure how to test this. Somehow I'd need to get an exception thrown before calling `HashDigestGZipStream.GetHash()`. Ideas welcome.
cc @baronfel @rainersigwald

Reorder disposing of the CryptoStream and HashAlgorithm to avoid ODE

---

azure-pipelines.yml

This is required by org policy now. Internal build showing it worked: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6978468&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=8ad2053a-945b-5371-5dad-8be76ffcb3f8

Enable CodeQL analysis

---

Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs

We observed SocketExceptions (closed from the remote end) in some not-
obviously-error cases when uploading to registries. Wrap a simple retry
loop with exponential backoff around the requests, being very specific
to just that exception.

Add retries for SocketExceptions

---

Microsoft.NET.Build.Containers/Registry.cs
containerize/Properties/launchSettings.json

This + retry seems to get uploads pretty reliable for ghcr.io and
azurecr.io, at least in my testing.

Upload all blobs as 64k chunks

---

docs/ContainerCustomization.md

@IEvangelist reached out to let me know that our docs were wrong about valid container names, so I'm updating that here (as well as an obsolete note about registry authentication).

Update docs on registry authentication and image naming

---

docs/ContainerCustomization.md
packaging/build/Microsoft.NET.Build.Containers.targets

Closes #148
Closes #165
Base images typically set ASPNETCORE_URLS to relevant port values, so we don't need to try to detect and override that ourselves.

Remove customizations for ASP.NET Core applications' ContainerEnvironmentVariables and ContainerPorts

---

Microsoft.NET.Build.Containers/AmazonECRMessageHandler.cs
Microsoft.NET.Build.Containers/Registry.cs
Test.Microsoft.NET.Build.Containers.Filesystem/RegistryTests.cs

*Note: I'm on the AWS .NET SDK team not the ECR team. I did some group debugging with the ECR team to understand the failures with this tooling pushing to ECR.*
This PR address the idiosyncrasy when pushing images to ECR.
* If the repository being pushed does not exist ECR abruptly ends the request. I believe that is why in the [RegistryAuthentication.md](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md#known-unsupported-registries) says the upload was cancelled for unknown reasons. I added special ECR error logic to look for the abrupt end to the request and inform the user they probably haven't created the repository yet.
* When doing the patch chunk uploads of the parts ECR returns back status code 201 (Created) instead of the standard 202 …

Fix issues pushing images to Amazon ECR

---

Microsoft.NET.Build.Containers/Registry.cs

This failed testing on baronfel/sdk-container-builds, but fixing the math made it work again.

Use more conservative upload size

---

Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs

When we lookup any stored credentials through the docker auth mechanism, we should use the registry as the key. This is the value that users are expected to interact with when 'priming' the config file. Our short-lived token cache can still use the `realm` here - the short-lived token cache has a subsequent step that reuses the token generated for the `realm` for calls to the `registry.
This works very well and actually ended up being something that fixed our GitHub test workflow (ignore the Google Cloud failure here): https://github.com/baronfel/sdk-container-demo/actions/runs/3887048885
Closes #284

Use separate cache keys for registry and realm

---

Microsoft.NET.Build.Containers/Registry.cs

Google Artifacts has a quirk where they do not support chunked uploads at all. Therefore, I introduced a capability check and factored out the decision of chunked or whole uploads and conditioned their registries to use the 'whole' strategy.  As a result, we're now green again on our test matrix! 
https://github.com/baronfel/sdk-container-demo/actions/runs/3887696305/jobs/6634248458
From [the documentation](https://cloud.google.com/artifact-registry/docs/reference/docker-api):
> Note: Artifact Registry does not support Docker [chunked uploads](https://docs.docker.com/registry/spec/api/#chunked-upload). Some container image tools support uploading large container images with either chunked uploads or a single [monolithic upload](https://docs.docker.com/registry/spec/api/#monolithic-upload). …

Refactor and fix Google Artifacts uploads

---

Microsoft.NET.Build.Containers/ContainerHelpers.cs
Test.Microsoft.NET.Build.Containers/ContainerHelpersTests.cs

Closes #290
Changes the validation regex to be 'alpha or underscore character, followed by zero or more alphanumeric or underscore characters', per the Posix spec section 8.1, replicated below
> These strings have the form name=value; names shall not contain the character '='. For values to be portable across systems conforming to POSIX.1-2017, the value shall be composed of characters from the portable character set (except NUL and as indicated below). There is no meaning associated with the order of strings in the environment. If more than one string in an environment of a process has the same name, the consequences are undefined.
> Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters, digits, and the …

Fix environment variable name validation

---

Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
containerize/Program.cs

Closes #297 
The parameter was required, but we weren't covering that case when a) constructing the CLI args in the ToolTask, and b) CLI parsing

make outputRegistry optional in containerize.exe as well

---

Directory.Packages.props
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/ArgumentEscaper.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/BasicCommand.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/Command.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/CommandResult.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/CommandResultAssertions.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/CommandResultExtensions.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/DotnetCommand.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/NativeMethods.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/ProcessReaper.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/SdkCommandSpec.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/StreamForwarder.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CommandUtils/TestCommand.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs
Test.Microsoft.NET.Build.Containers.Filesystem/DockerRegistryManager.cs
Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs
Test.Microsoft.NET.Build.Containers.Filesystem/LayerEndToEnd.cs
Test.Microsoft.NET.Build.Containers.Filesystem/ProjectInitializer.cs
Test.Microsoft.NET.Build.Containers.Filesystem/RegistryTests.cs
Test.Microsoft.NET.Build.Containers.Filesystem/Test.Microsoft.NET.Build.Containers.Filesystem.csproj
Test.Microsoft.NET.Build.Containers.Filesystem/ToolsetUtils.cs

- ported command utils from dotnet/sdk (https://github.com/dotnet/sdk/tree/main/src/Tests/Microsoft.NET.TestFramework)
- replaced `Process.Start` with utils - allows better error reporting in first place
- enabled nullables
- added KISS `dotnet` path resolver (inspired by https://github.com/dotnet/sdk/blob/main/src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs)

added command utils, refactored tests

---

Microsoft.NET.Build.Containers/Layer.cs
Microsoft.NET.Build.Containers/LocalDocker.cs
Test.Microsoft.NET.Build.Containers.Filesystem/LayerEndToEnd.cs

This PR adds the following changes which are all related to https://github.com/dotnet/sdk-container-builds/issues/304 
1. It changes the Tar writing to use `Pax`. This seem to be the default in `docker save`, in [.net](https://github.com/dotnet/runtime/blob/58719ec90b3bbae527dd81685bf8670b993fe8f9/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.cs#L31) 
2. It ensures that for each file added to the Tar, the respective directory entries are also created. I first though of merging `Layer.FromDirectory` and `Layer.FromFiles` and then traverse the FS tree building the items but I decided against it then. I found some tests aiming to support a list of files from different directories. 
3. Added a missing using to the `TarWriter` writing the file sent to docker. 
On a Windows …

Fix Tar writing to include directory records

---

Microsoft.NET.Build.Containers/KnownStrings.cs
Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs
docs/ContainerCustomization.md
packaging/build/Microsoft.NET.Build.Containers.targets

Closes https://github.com/dotnet/sdk-container-builds/issues/96
This fills in the metada in #96 using project properties. There are conditionals for the entire generation as well as each specific item. The properties are patterned after the NuGet [pack targets](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target) mappings.
The only caveat is that the source control urls aren't flowed through unless the `PublishRepositoryUrl` property is set to true, following guidance from the sourcelink repo.

Fill in conventional labels from existing project metadata

---

docs/ContainerCustomization.md

Based on [this conversation on Twitter](https://twitter.com/Aaronontheweb/status/1623059659115360256) we should make it as clear as possible which config knobs are properties vs items. I've wrapped all properties in `<PropertyGroup>` elements to hopefully make that clearer.

Wrap property examples in PropertyGroup elements to help signal properties vs items

---

Microsoft.NET.Build.Containers/BaseImageNotFoundException.cs
Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/CreateNewImage.Interface.cs
Microsoft.NET.Build.Containers/CreateNewImage.cs
Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
Microsoft.NET.Build.Containers/Image.cs
Microsoft.NET.Build.Containers/ImageReference.cs
Microsoft.NET.Build.Containers/LocalDaemons/ILocalDaemon.cs
Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Microsoft.NET.Build.Containers/Registry.cs
Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs
Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs
Test.Microsoft.NET.Build.Containers/DockerDaemonTests.cs
containerize/Program.cs
packaging/build/Microsoft.NET.Build.Containers.targets

This PR takes the chance to define an interface for working with a local container daemon of some kind, refactors the existing `LocalDocker` code to use that interface, and adds an explicit check for that local daemon before use.
Closes #278

Extract an interface for local daemons, and check for local docker daemon activity.

---

packaging/build/Microsoft.NET.Build.Containers.targets

This updates the logic used to identify Asp.NET/SelfContainer projects to allow the dependent ContainerBaseImage to be a top level property rather than having to be calculated in the ComputeContainerConfig target. This makes the targets much easier to work with from outside of MSBuild (particularly in VS/VScode extensions) if one wants to determine the base image that the SDK will use.
The `UsingMicrosoftNETSdkWeb` property is set to true by the Asp.NET SDK before the Microsoft.NET.Build.Containers targets would be run (unlike the AspNetCore capability) and the Microsoft.AspNetCore.App framework reference should also be set early enough to be depended on for a top level property.

Make base image properties top level

---

Directory.Build.props
Directory.Packages.props
Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/CommandResultAssertions.cs
Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/DotnetCommand.cs
Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/SdkCommandSpec.cs
Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/StreamForwarder.cs
Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/TestCommand.cs
Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
Microsoft.NET.Build.Containers.UnitTests/Microsoft.NET.Build.Containers.UnitTests.csproj
Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
containerize/containerize.csproj

Implemented validation and added tests for generating parameters for `containerize`
TODO:

validation and tests in `CreateNewImageToolTask`

---

docs/RegistryAuthentication.md

We no longer need this caveat based on testing from our friends from the VS Publish team.

Update note on compatiblity with Azure Container Registry Authentication

---

.editorconfig
Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
Microsoft.NET.Build.Containers.UnitTests/ImageBuilderTests.cs
Microsoft.NET.Build.Containers.UnitTests/ImageConfigTests.cs
Microsoft.NET.Build.Containers.UnitTests/Microsoft.NET.Build.Containers.UnitTests.csproj
Microsoft.NET.Build.Containers.UnitTests/Resources/ResourceTests.cs
Microsoft.NET.Build.Containers/Constants.cs
Microsoft.NET.Build.Containers/ImageConfig.cs
Microsoft.NET.Build.Containers/Layer.cs
Microsoft.NET.Build.Containers/PublicAPI/net7.0/PublicAPI.Unshipped.txt
Microsoft.NET.Build.Containers/Resources/Resource.cs
Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs

I was looking towards support for `scratch` containers, and I reasoned that I still wanted to use the `ImageConfig` type to store all of the user-supplied information, but in the case of the 'scratch' image there would be no base config. Therefore some of the required properties in a configuration would need to be specified more manually. So I elevated them to first-class fields in the ImageConfig type.
As part of that, I got around to an item I've wanted to do for a while - adding a log to the History collection in the config to trace the fact that _we_ made one of the layers.
Here's what the history of one of our generated test containers looks like when viewed under `docker history <imagename>`:
Docker Desktop also has a more detailed view:

Support History/Build configs in an immutable way

---

Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/ImageBuilder.cs
Microsoft.NET.Build.Containers/ImageConfig.cs
Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
Microsoft.NET.Build.Containers/PublicAPI/net7.0/PublicAPI.Unshipped.txt
Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
containerize/Program.cs
packaging/build/Microsoft.NET.Build.Containers.targets

There is no validation on this, as it's _very_ hard to do - the supported formats are
* user name
* user id
* user name:group name
* user id:group id
* user id:group name
* user name:group id
all of which should match either a name or an id from `/etc/passwd`, which we theoretically have access to through the layers, but that seems _really_ extra to acquire, unTAR, parse and validate.
Closes #115

Add support for setting the `User` metadata item

---

Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Microsoft.NET.Build.Containers/ContainerBuilder.cs
Microsoft.NET.Build.Containers/ImageBuilder.cs
Microsoft.NET.Build.Containers/ImageConfig.cs
Microsoft.NET.Build.Containers/Layer.cs
Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
packaging/build/Microsoft.NET.Build.Containers.targets

Related Issue: https://github.com/dotnet/sdk-container-builds/issues/117
Key change in this PR are: 
1. Handle Windows RIDs in EntryPoint and WorkingDir of images
2. Change the Layer Tar structure to the one needed for Windows layers with `Files/` and `Hives/` and not having a drive letter folder. 
3. Ensure we have the a Security Identifiers set as PAX header for the tar entries allowing `BUILTIN\Users` access to the app folder. 
4. Adopted [this remark](https://github.com/dotnet/sdk-container-builds/pull/323#discussion_r1098544735) from my previous rework to pull the `EnsureDirectoryEntries` into a local function.  
5. I added a test which checks for the expected folder structure of Windows layer. Further tests might be added once there is a Windows Container Runtime available in the CI …

Extend Layer Packaging for Windows Containers

---

Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
Microsoft.NET.Build.Containers/Resources/Strings.resx

Fixes #329
CONTAINER1xxx: HTTP or local daemon related failures
CONTAINER2xxx: Invalid/missing data related failures
CONTAINER3xxx: Docker process related failures

Added codes to messages

---

Microsoft.NET.Build.Containers.IntegrationTests/CapturingLogger.cs
Microsoft.NET.Build.Containers.IntegrationTests/ParseContainerPropertiesTests.cs
Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
docs/ContainerCustomization.md
packaging/build/Microsoft.NET.Build.Containers.targets

Fix #373
Defaults the ContainerUser to platform-specific non-root users when targeting .NET 8 and above.

Default the ContainerUser to rootless users on .NET 8 and above

---

DEVGUIDE.md
README.md
docs/DevelopmentDocumentation.md

fixes https://github.com/dotnet/sdk-container-builds/issues/408
The documentation is based on https://github.com/dotnet/sdk/pull/31432/

Updated development documentation

---

docs/ContainerCustomization.md

These are the doc updates for https://github.com/dotnet/sdk/pull/32473

explain more about RIDs

---

docs/ContainerCustomization.md

Fixes https://github.com/dotnet/sdk-container-builds/issues/462

Update ContainerCustomization.md to note changes to `ContainerImageTag` in .NET 8

---

docs/RegistryAuthentication.md

Fixes https://github.com/dotnet/sdk-container-builds/issues/571

Add docs about supporting insecure registries

---

docs/ContainerCustomization.md

Specify that `ContainerRuntimeIdentifier` can be plural for multi-architecture image scenarios and give an example.

Specify that ContainerRuntimeIdentifier can be plural
