dotnet/sdk-container-builds

- System.Containers/Image.cs
- System.Containers/Registry.cs
- containerize/Program.cs
this is a tiny stab to let us manipulate the working directory. more a little exploration than anything else.
> add mechanism to get/set Workingdir of the image configuration

- .github/workflows/dotnet.yml
- Directory.Build.props
- Directory.Packages.props
- Test.System.Containers.Filesystem/EndToEnd.cs
- version.json
Bump versions automatically by git commit height.
> Introduce Nerdbank.GitVersioning

- System.Containers.Tasks/ParseContainerProperties.cs
- Test.System.Containers.Filesystem/DockerRegistryManager.cs
- Test.System.Containers.Filesystem/LayerEndToEnd.cs
- Test.System.Containers.Filesystem/ParseContainerPropertiesTests.cs
- Test.System.Containers.Filesystem/Test.System.Containers.Filesystem.csproj
https://github.com/rainersigwald/containers/pull/51 should merge first
> Add ParseContainerProperties & Tests

- nuget.config
> Add package source mapping

- docs/INTEGRATED-DEMO.md
This isn't exhaustive, and will change as soon as @BenVillalobos's target changes merge in, but I wanted to get down the 'current state'.
> add a quick markdown of the steps to go from zero to running for the current version

- System.Containers.Tasks/CreateNewImage.cs
- System.Containers.Tasks/build/System.Containers.Tasks.props
- System.Containers.Tasks/build/System.Containers.Tasks.targets
- System.Containers/Image.cs
- Test.System.Containers.Filesystem/CreateNewImageTests.cs
merge after https://github.com/rainersigwald/containers/pull/52
> Update CreateNewImage & Add Tests

- Directory.Solution.targets
- System.Containers.Tasks/ParseContainerProperties.cs
- System.Containers.Tasks/build/System.Containers.Tasks.props
- System.Containers.Tasks/build/System.Containers.Tasks.targets
- Test.System.Containers.Filesystem/DockerRegistryManager.cs
- Test.System.Containers.Filesystem/EndToEnd.cs
merge after https://github.com/rainersigwald/containers/pull/53/
> Update Props, Targets, & Tasks

- docs/INTEGRATED-DEMO.md
With the bevy of recent changes, getting started is a _lot_ simpler. Now the most onerous part is getting the package, and that's being handled by Rainer as we speak!
> update guidance to get a lot simpler

- System.Containers/Registry.cs
This is needed for a rename later.
> Simplify some namespaces

- Microsoft.NET.Build.Containers/CreateNewImage.cs
- Microsoft.NET.Build.Containers/LocalDocker.cs
- Microsoft.NET.Build.Containers/Registry.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs
- containerize/Program.cs
Instead of hardcoding "latest" everywhere.
Fixes #60.
> Support passing tag

- containerize/Program.cs
> Delete unused PushToLocalDockerViaRegistry

- Microsoft.NET.Build.Containers/LocalDocker.cs
- global.json
- .NET 7 preview7
- Adopt some new async tar APIs
> Adopt .NET 7 preview 7

- Microsoft.NET.Build.Containers/ContainerHelpers.cs
- Microsoft.NET.Build.Containers/ParseContainerProperties.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/CreateNewImageTests.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/ParseContainerPropertiesTests.cs
- Test.Microsoft.NET.Build.Containers/ContainerHelpersTests.cs
Merge after https://github.com/rainersigwald/containers/pull/54
> Add IsValidRegistry, Ensure ports flow with registries

- Microsoft.NET.Build.Containers/Image.cs
> Update timestamp when modifying config

- Microsoft.NET.Build.Containers/build/Microsoft.NET.Build.Containers.targets
> Entrypoint args to CreateNewImage are now arrays

- Microsoft.NET.Build.Containers/CreateNewImage.cs
- Microsoft.NET.Build.Containers/DockerLoadException.cs
- Microsoft.NET.Build.Containers/LocalDocker.cs
We may want to have a more sophisticated way of dealing with this in the future
but this gives users a fighting chance of understand what went wrong + better
error reports for us.
> Detect and report docker load errors

- docs/INTEGRATED-DEMO.md
@Forgind was kind enough to try running through the demo from scratch and ran into some speedbumps. Clarify various aspects of the process.
> First dogfooder doc feedback

- Microsoft.NET.Build.Containers/ContainerHelpers.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs
> Cherry-pick More correct image name normalization (#119) to v0.1 release

- Microsoft.NET.Build.Containers/ContainerHelpers.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/TargetsTests.cs
This one has the correct base branch
> Cherry pick to v0.1 - More correct image name normalization (#119)

- Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
I did check that the generated nuget package has the correct url.
> Fix v0.1 repo url

- DEVGUIDE.md
Add steps to test a locally built NuGet package.
cc @baronfel @rainersigwald @BenVillalobos
> Update DEVGUIDE for local testing

- Microsoft.NET.Build.Containers/ContainerHelpers.cs
- Microsoft.NET.Build.Containers/CreateNewImage.cs
- containerize/Program.cs
- containerize/Properties/launchSettings.json
Supports all inputs required for CreateNewImage. Has some validation on labels (I'm forcing x=y format on that).
Build logic to ship this comes later.
> Update containerize to prep for shipping

- global.json
Keeping up with latest.
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-rc-1/
> Move to .NET 7 RC.1

- docs/ContainerCustomization.md
We implemented these earlier and didn't update docs
> add docs for ports and labels

- .github/workflows/dotnet.yml
> Enable warnAsError in CI build

- Test.Microsoft.NET.Build.Containers.Filesystem/EndToEnd.cs
Isolate the NuGet store used by tests so that it doesn't install to the
main location, possibly confusing local builds and missing changes.
> Simplify NuGet restoration in tests

- Microsoft.NET.Build.Containers/Image.cs
This wasn't being updated and some registries/consumers appear to care.
> Update size in UpdateDigest()

- Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
- Microsoft.NET.Build.Containers/Registry.cs
I extracted this from #208 because I'm a good person.
> Support parallel upload of blobs

- global.json
This came out like a whole week ago, I feel so behind :).
> .NET SDK 7.0.100-rc.2

- Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
- Microsoft.NET.Build.Containers/ContainerHelpers.cs
- Microsoft.NET.Build.Containers/ContainerHttpException.cs
- Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
- Microsoft.NET.Build.Containers/DockerLoadException.cs
- Microsoft.NET.Build.Containers/Registry.cs
- Microsoft.NET.Build.Containers/VSHostObject.cs
Cleanup PR post-https://github.com/dotnet/sdk-container-builds/pull/204
Each commit is a direct response to a comment/suggestion made on the previous PR.
> HostObject Cleanup

- .github/workflows/dotnet.yml
- Enable checks on release branches
- Enable manual workflow dispatch
> Checks for release branches

- Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
- Microsoft.NET.Build.Containers/VSHostObject.cs
Adds extra logging for the VS auth scenario
> Log a warning when hostobject found with no creds

- version.json
I fast-forwarded main to the 0.2 release branch instead of merging it + doing this, mea culpa.
> Bump version to 0.3

- docs/RegistryAuthentication.md
For GA we're having issues with AWS ECR and GitHub Package Registry - let's note that here. I'll also log an issue about what we're seeing.
> note issues with AWS/GitHub at time of release

- Microsoft.NET.Build.Containers/Registry.cs
This is cheap to implement and provides (me, at least) a bit more reassurance that things are going to the right place.
> Name registry in progress messages

- .github/workflows/dotnet.yml
- Microsoft.NET.Build.Containers/CreateNewImageToolTask.cs
- packaging/build/Microsoft.NET.Build.Containers.targets
Pull the last late-breaking fixes back.
> Merge 0.2 release branch to main

- Microsoft.NET.Build.Containers/Layer.cs
IncrementalHash is easier to use and less error prone.
Fix #253
cc @bartonjs @baronfel
> Use IncrementalHash instead of CryptoStream

- DEVGUIDE.md
- docs/ContainerCustomization.md
- docs/GettingStarted.md
This is the in-repo docs for #301 and part of #299 - the remainder should be done on learn.ms.com after this.
> Update docs for musl and 7.0.2xx inclusion

- Microsoft.NET.Build.Containers/ContainerBuilder.cs
- Microsoft.NET.Build.Containers/CreateNewImage.cs
- Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
- Test.Microsoft.NET.Build.Containers.Filesystem/ParseContainerPropertiesTests.cs
- packaging/build/Microsoft.NET.Build.Containers.targets
fixes https://github.com/dotnet/sdk-container-builds/issues/320
The following project capability is added in targets:
`<ProjectCapability Include="NetSdkOCIImageBuild" />`
> Added `NetSdkOCIImageBuild` `ProjectCapability` to targets

- .editorconfig
- Microsoft.NET.Build.Containers/CreateNewImage.cs
- Microsoft.NET.Build.Containers/Image.cs
- Microsoft.NET.Build.Containers/KnownStrings.cs
- Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
- Microsoft.NET.Build.Containers/ReferenceParser.cs
- Microsoft.NET.Build.Containers/Registry.cs
fixes https://github.com/dotnet/sdk-container-builds/issues/330
Fixes occurrences of CA1051 and CA2211:
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211
> Fixes occurrences of CA1051 and CA2211

- docs/ReleaseNotes/v0.4.0.md
- packaging/package.csproj
Doing this makes the prerelease packages more useful, and lets us update the release notes as we merge other PRs.
> initial release notes for v4 to track as we go (#335)Co-authored-by: Vlada Shubina <vshubina@microsoft.com>

- Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
- Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
- Microsoft.NET.Build.Containers/Resources/Strings.resx
> Fixed error messages

- docs/RegistryAuthentication.md
As requested in https://github.com/dotnet/sdk-container-builds/discussions/359
> Add clarifications about docker.io as a registry source or destination

- Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
- Microsoft.NET.Build.Containers/Registry.cs
- Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
Adds diagnostic logging, fixes a GCP detection regression, and fixes the final stdout reporting for layer pushes.
> A few fixes around diagnostic logging that I found while debugging pushes to AWS, GCP, and GitHub Packages

- Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/CommandResultAssertions.cs
- Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
- Microsoft.NET.Build.Containers.IntegrationTests/ParseContainerPropertiesTests.cs
- Microsoft.NET.Build.Containers.UnitTests/DiagnosticMessageTests.cs
- Microsoft.NET.Build.Containers.UnitTests/Resources/ResourceTests.cs
- Microsoft.NET.Build.Containers/ContainerBuilder.cs
- Microsoft.NET.Build.Containers/DiagnosticMessage.cs
- Microsoft.NET.Build.Containers/Globals.cs
- Microsoft.NET.Build.Containers/KnownStrings.cs
- Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
- Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
- Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
- Microsoft.NET.Build.Containers/PublicAPI/net7.0/PublicAPI.Unshipped.txt
- Microsoft.NET.Build.Containers/Resources/Resource.cs
- Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
- Microsoft.NET.Build.Containers/Resources/Strings.resx
- Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
- Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
- Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
- Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
- containerize/Program.cs
> Containerize error formatting

- docs/ContainerCustomization.md
- docs/RegistryAuthentication.md
Fixes #486
Fixes #463
Fixes #461 
Fixes #487
> Document changes for 8.0.100

- docs/RegistryAuthentication.md
Docs changes around authentication and registry workarounds for .NET 8.0.100.
> Update RegistryAuthentication.md to account for .NET 8 updates

- docs/ContainerCustomization.md
The '/' of a closing tag was missing
> Update ContainerCustomization.md typo

- docs/RegistryAuthentication.md
From 9.0.100 onwards
Fixes #577
> Add env var insecure registry example

- docs/RegistryAuthentication.md
related to https://github.com/dotnet/sdk/commit/7969bf8f0b084a0d3236964ac6b1c862118e66d7
> Update docs for DOTNET_CONTAINER environment vars
